<?php  
	session_start();
	$conn=mysqli_connect('localhost','root','');
	mysqli_select_db($conn,'myfirstdb2');
	$email=$_POST['email'];
	$pass=$_POST['password'];
	$username=$_POST['username'];
	$s="select * from firsttable where email='$email' && password='$pass'";
	$result=mysqli_query($conn,$s);
	$num=mysqli_num_rows($result);
	if($num==1){
		$_SESSION['email']=$email;
		header('location:account.php');
	}
	else
	{
		header('location:login.html');
	}
?>